modLoader="javafml"
loaderVersion="[47,)"
license="MIT"

[[mods]]
modId="elbowstrike"
version="${file.jarVersion}"
displayName="Elbow Strike"
description='''
按 M 键对前方生物进行肘击
'''

[[dependencies.elbowstrike]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.elbowstrike]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"